# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  format:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/spotxchange/hydra
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: dep ensure -vendor-only
      - run: ./scripts/test-format.sh

  test:
    docker:
      - image: circleci/golang:1.9
        environment:
        - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/hydra?sslmode=disable
        - TEST_DATABASE_MYSQL=root:test@(localhost:3306)/mysql?parseTime=true
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=hydra
      - image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=test
    working_directory: /go/src/github.com/spotxchange/hydra
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: go get -u github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/ory/go-acc
      - run: dep ensure -vendor-only
      - run: go install github.com/spotxchange/hydra
      - run: go-acc -o coverage.txt ./...
      - run: go test -race -short $(go list ./... | grep -v cmd)
      - run: ./scripts/test-e2e.sh
      - run: goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN

  swagger:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/spotxchange/hydra
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: go get -u github.com/go-swagger/go-swagger/cmd/swagger golang.org/x/tools/cmd/goimports
      - run: dep ensure -vendor-only
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y default-jre nodejs
      - run: sudo npm i -g yarn
      - run: yarn
      - run: ./scripts/test-sdk.sh

  build-docker:
    docker:
      - image: library/docker:17.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run: docker build -f Dockerfile -t hydra-test .
      - run: docker build -f Dockerfile-alpine -t hydra-test-alpine .
      - run: docker run hydra-test help

  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/spotxchange/hydra
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      # Environment dependencies
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: go get -u github.com/mitchellh/gox github.com/tcnksm/ghr
      - run: dep ensure -vendor-only
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      # Build binaries for GitHub
      - run: ./scripts/run-deploy.sh
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/
      # Build and push docker image
      - run: docker build --build-arg git_tag=$(git describe --tags) --build-arg git_commit=$(git rev-parse HEAD) -f Dockerfile -t oryd/hydra:$CIRCLE_TAG .
      - run: docker build --build-arg git_tag=$(git describe --tags) --build-arg git_commit=$(git rev-parse HEAD) -f Dockerfile-alpine -t oryd/hydra:$CIRCLE_TAG-alpine .
      - run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run: docker push oryd/hydra:$CIRCLE_TAG
      - run: docker push oryd/hydra:$CIRCLE_TAG-alpine
      # Release node / JavaScript SDK
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: sudo npm i -g npm
      - run: npm view ory-hydra-sdk
      - run: npm publish

  changelog:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: gem install github_changelog_generator
      - run: sudo npm i -g doctoc
      - run: github_changelog_generator -u ory -p hydra -o CHANGELOG.md --token $GITHUB_TOKEN
      - run: doctoc CHANGELOG.md
      - run: git config --global user.email "circleci@ory.am"
      - run: git config --global user.name "ORY Continuous Integration"
      - run: git add CHANGELOG.md
      - run: |
          git commit -m "docs: Incorporates changes from version $(git describe --tags)" -- CHANGELOG.md
      - run: git remote rm origin
      - run: git remote add origin https://arekkas:$GITHUB_TOKEN@github.com/spotxchange/hydra.git
      - run: git push origin HEAD:master

workflows:
  version: 2
  "test, build, push, and deploy":
    jobs:
      - format:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - swagger:
          filters:
            tags:
              only: /.*/
      - build-docker:
          requires:
            - test
            - swagger
            - format
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build-docker
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - changelog:
          requires:
            - release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
